"""init

Revision ID: 1ee628dffd64
Revises: 
Create Date: 2026-07-21 15:00:52.207991

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "1ee628dffd64"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
