"""add_indexes

Revision ID: b97076f2ace6
Revises: 6e8edec7d0c9
Create Date: 2026-07-21 15:03:17.319089

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b97076f2ace6"
down_revision: Union[str, None] = "6e8edec7d0c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_inventory_category", "inventory", ["category"], unique=False)
    op.create_index(
        "ix_inventory_department", "inventory", ["department"], unique=False
    )
    op.create_index(
        "ix_inventory_inventory_number", "inventory", ["inventory_number"], unique=False
    )
    op.create_index(
        "ix_inventory_invoice_number", "inventory", ["invoice_number"], unique=False
    )
    op.create_index("ix_inventory_item_name", "inventory", ["item_name"], unique=False)
    op.create_index(
        "ix_inventory_serial_number", "inventory", ["serial_number"], unique=False
    )
    op.create_index("ix_inventory_status", "inventory", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_inventory_status", table_name="inventory")
    op.drop_index("ix_inventory_serial_number", table_name="inventory")
    op.drop_index("ix_inventory_item_name", table_name="inventory")
    op.drop_index("ix_inventory_invoice_number", table_name="inventory")
    op.drop_index("ix_inventory_inventory_number", table_name="inventory")
    op.drop_index("ix_inventory_department", table_name="inventory")
    op.drop_index("ix_inventory_category", table_name="inventory")
    # ### end Alembic commands ###
